cargo-features = ["workspace-inheritance"]

[package]
name = "snowflake-util"
version = "0.0.0"
edition = "2021"

[dependencies]
blake3_c_rust_bindings.workspace = true
thiserror.workspace = true

[dependencies.os-ext]
path = "../common/os-ext"
