[package]
name = "snowflake"
version = "0.0.0"
edition = "2021"

[dependencies.blake3_c_rust_bindings]
git = "https://github.com/BLAKE3-team/BLAKE3"
rev = "1.3.1"

[dependencies.os-ext]
path = "../common/os-ext"

[dev-dependencies.scope-exit]
path = "../common/scope-exit"
